### ISSUE TITLE
Warning: Identifier uniqueness violation

### ISSUE THREAD

**Issue by Siccity** [Siccity/GLTFUtility#10]
Message appears as a yellow warning in console on import of some models (example ReciprocatingSaw from https://github.com/KhronosGroup/glTF-Sample-Models) without any further information or stack trace
```
Identifier uniqueness violation: 'Material_22'. Scripted Importers do not guarantee that subsequent imports of this asset will properly re-link to these targets.
```

**Comment by Paegasus** [comment]
Alright, I downloaded the latest commit, and it seems to be working fine now, thanks a lot,
it already looks like a great alternative to Khronos' UnityGLTF.
<img src="https://i.imgur.com/kHGQuSq.jpg"><image>
