### ISSUE TITLE
draco/README.md has no meta file.

### ISSUE THREAD

**Issue by CodeTako-Ball** [Siccity/GLTFUtility#105]
Unity throws an error when importing GLTFUtility via manifest.json and UPM:
`Read only asset Packages/com.siccity.gltfutility/Plugins/draco/README.md has no meta file.`

**Comment by SquishyPandaDev** [comment]
Getting this issue too with Unity 2019.4.12f1. Full error message is

```
Packages/com.siccity.gltfutility/Plugins/draco/README.md has no meta file, but it's in an immutable folder. The asset will be ignored
```
