### ISSUE TITLE
Plugin 'libdracodec_unity.so' is used from several locations

### ISSUE THREAD

**Issue by marlon360** [Siccity/GLTFUtility#113]
I receive this error when building the latest version for iOS:

> Plugin 'libdracodec_unity.so' is used from several locations:
 Packages/com.siccity.gltfutility/Plugins/draco/Plugin/Android/armeabi-v7a/libdracodec_unity.so would be copied to <PluginPath>/libdracodec_unity.so
 Packages/com.siccity.gltfutility/Plugins/draco/Plugin/Android/arm64-v8a/libdracodec_unity.so would be copied to <PluginPath>/libdracodec_unity.so
Please fix plugin settings and try again.

I imported the package via the Package Manager.
So I cannot exclude the plugins for specific targets. The Plugin Inspector is grayed out.

**Comment by oscar-green** [comment]
![image](https://user-images.githubusercontent.com/5816547/97423128-12782680-190f-11eb-81b4-c880c055dc76.png)

Yes for some reason xcode wants to include the android plugins in the iOS build. I solved this locally by excluding iOS from the android plugins (Android/arm64-v8a and Android/armeabi-v7a)

**Comment by marlon360** [comment]
@oscar-green This works if you import the package directly into the project.

However if you import the package via Unity Package Manger like so:
```json
{
  "dependencies": {
    "com.siccity.gltfutility": "https://github.com/Siccity/GLTFUtility.git#507cf88b5ab4faac46e8ef132e95134acda2865d"
  }
}
```

You cannot set the platforms for the plugin:
![gltf_package_plugin](https://user-images.githubusercontent.com/11810704/97424494-14db8000-1911-11eb-904b-9eeecd685f88.png)

**Comment by oscar-green** [comment]
Yeah, it was more of a comment to the devs on how to fix it

**Comment by ABinettiCap** [comment]
I have the same error for Universal Window Platform, but i can't exclude IOS or Android from the libracodec_unity ... I tried to import the package with package manager and manually but i have the error anyway.

**Comment by Siccity** [comment]
I pushed @oscar-green 's suggestion 871d0a96745a2c916b83484bf8ef53b863a0ed1b.
Please update and see if it works for you

**Comment by ABinettiCap** [comment]
Problem solved for me ! Thank you !
