### ISSUE TITLE
Node matrix not parsed on iOS

### ISSUE THREAD

**Issue by daverin** [Siccity/GLTFUtility#114]
For some reason, the matricies of the glTF nodes are not being parsed on iOS. 

<img src="https://user-images.githubusercontent.com/70378377/98820366-bd700080-2436-11eb-9573-ffa202a8667f.PNG" height=400>

[Orientation test](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/OrientationTest) on iOS. 

Seems [this](https://github.com/Siccity/GLTFUtility/blob/695ab4d350fc1865d88ade168ed02c8b899334ad/Scripts/Spec/GLTFNode.cs#L19) setter is not being called. 

Any help would be greatly appreciated.

**Comment by dri-richard** [comment]
This seems to be an IL2CPP issue (I can repro similar in Windows and Android IL2CPP builds), I merged your fix into my fork, thanks.

**Comment by nolimet** [comment]
managed to repoduce it aswell on Unity 2019,4,18f1. 
Found out that the issue was that the matrix got stripped.
Seems like that unity will ignore the Preserve tag sometimes and just strip regardless.
