### ISSUE TITLE
OpenUPM Package?

### ISSUE THREAD

**Issue by De-Panther** [Siccity/GLTFUtility#116]
Great package!

Using git for packages is simple for most cases, but it won't show updates on the Package Manager window in Unity.
It's also a problem to add dependencies for this package from other packages...

There's https://openupm.com/
That serve packages from its `scopedRegistries`.

This repo is mostly compatible, the only thing missing is to update the Releases/Tags according to the OpenUPM needs.

Can you please add it to OpenUPM or another UPM service?

**Comment by De-Panther** [comment]
I see that someone already added the package to OpenUPM, but because there's no valid Git tag, it doesn't work.
https://openupm.com/packages/com.siccity.gltfutility/

**Comment by hybridherbst** [comment]
@Siccity to bring this up again, to make GLTFUtility properly be usable from OpenUPM, all that needs to be done is change the tag format to Major.Minor.Patch - 
would be great if you could tag 0.7 with "0.7.0", 0.6 with "0.6.0". Thank you!

**Comment by Siccity** [comment]
Added 0.7.1 tag
