### ISSUE TITLE
Tag version does not match version in package.json

### ISSUE THREAD

**Issue by hybridherbst** [Siccity/GLTFUtility#130]
As a follow-up to #116 ,

the tag should match the version in package.json, and the package.json version needs to be bumped if you want to have an updated package.

E.g. right now the tag is 0.7.1 but in package.json is 0.6.0, thus OpenUPM shows 0.6.0 (same as Unity PackMan if you use the current version directly as git package): https://openupm.com/packages/com.siccity.gltfutility/?subPage=versions

So, recommendation: bump package.json to 0.7.2 and make a 0.7.2 tag, and going forward try to keep these in sync :)

Thanks!

**Comment by Siccity** [comment]
I'll update it but
Is there any particular reason for this redundancy? I don't use any package managers myself, so I fail to see the usefulness of this.

**Comment by hybridherbst** [comment]
The way to go for external code in Unity is UPM packages.
These always have a version, and can be identified as such from the Unity Package Manager. The version is important for dependency management. - that's the reason for having the right version in package.json.

The reason why OpenUPM has a specific format for tags that "trigger rebuilds" is just that this allows you to have other tags that don't automatically trigger a rebuild. E.g. if you had a "last-version-to-support-X" tag that does not trigger a package update for the OpenUPM automatism. I think by default it just looks for a Semver-compatible tag and then kicks of the new version.

Maybe @favo has more input here as well, but I think that's the gist of it :)

(e.g. for our packages we have set up OpenUPM to only look for tags that start with "release/" followed by a SemVer)
