### ISSUE TITLE
Will not nload gltf on iOS but same code works on Android

### ISSUE THREAD

**Issue by alexs7** [Siccity/GLTFUtility#133]
I am downloading a model and then loading it as:

```
string modelPath = Path.Combine(Application.persistentDataPath, model_file_name);
Debug.Log("Loading, model from disk...");
Debug.Log(Application.persistentDataPath);
Importer.ImportGLTFAsync(modelPath, new ImportSettings(), OnFinishAsync, OnProgress);
```

And on XCode I get this:

```
Mesh 12 import error
Siccity.GLTFUtility.<OnCoroutine>d__5:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
Siccity.GLTFUtility.<TaskSupervisor>d__17:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

Not sure what is going wrong here ? Any help ?

**Comment by Siccity** [comment]
Try loading it sync, see if that error is more helpful

**Comment by alexs7** [comment]
The problem was with the draco compression. sometimes when you use draco compression, the loader does not work on iOS.

**Comment by seancheno** [comment]
I am receiving same error with draco compressed models on IOS. Any potential fix for this or should we just stay away from draco compression for now?

**Comment by atulafternow** [comment]
@Siccity  and @paul-bonnel-fr  Yes I am facing the same issue Draco compressed glbs is not working on uwp and ios.
when I was looking for the reason for this issue and found that we don't have Draco dll for UWP and iOS and that's why it's not working.

**Comment by Siccity** [comment]
Unfortunately I do not have a Mac to test with. I can only wait for a pull request

**Comment by atulafternow** [comment]
Hey, @Siccity could you plz tell me which Draco repository u have used?

**Comment by paul-bonnel-fr** [comment]
I've tried importing the iOS draco plugin for Unity from this repo https://github.com/google/draco/tree/master/unity/Plugin without success any ideas ?

**Comment by Siccity** [comment]
@atulafternow 
https://gitlab.com/atteneder/DracoUnity

**Comment by atulafternow** [comment]
@Siccity @paul-bonnel-fr i have tested the fix for ios and testing it on UWP once that I'll make a PR.

**Comment by hdeppert** [comment]
I see #166 is already merged, so this issue should be fixed?

**Comment by FreshlyBrewedCode** [comment]
I am unable to load a Draco compressed .glb file on HoloLens 2 (UWP ARM64). I tried loading it syncronously from file and asynchronously from byte array but I the logs show the same error:
```
Mesh 0 import error
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Siccity.GLTFUtility.<OnCoroutine>d__5:MoveNext()
Siccity.GLTFUtility.ImportTask`1:RunSynchronously()
Siccity.GLTFUtility.Importer:LoadInternal(GLTFObject, String, Byte[], Int64, ImportSettings, AnimationClip[]&)
Siccity.GLTFUtility.Importer:ImportGLB(String, ImportSettings, AnimationClip[]&)
Siccity.GLTFUtility.Importer:LoadFromFile(String, ImportSettings, AnimationClip[]&, Format)
Siccity.GLTFUtility.Importer:LoadFromFile(String, ImportSettings, Format)
GLTFImportTest:Start()
```

The logs also show that the `dracodec_unity.dll` is loaded:
```
Loading native plugins
  Loading dracodec_unity.dll
```

The same model does load without problems in the Unity editor running on Windows. 

One of the models I used for testing was: https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Duck/glTF-Binary/Duck.glb compressed using `gltf-pipeline`. 

Any suggetions for further troubleshooting?

**Comment by tafkag** [comment]
@FreshlyBrewedCode I have the exact same issue ("Mesh 0 import error), trying to import a draco compressed gltf file from the StreamingAssets folder on Hololens 2. Did you find a solution to your problem? 

I can load non-compressed files without any problems and copied the WSA/ARM64 dracodec_unity.dll into the Plugins folder, but can't get past the import error message.

**Comment by FreshlyBrewedCode** [comment]
@tafkag I never found a fix unfortunately.

**Comment by beyondnations** [comment]
still no fix for this? draco compression problem on ios?
