### ISSUE TITLE
How to load GLTF file at runtime

### ISSUE THREAD

**Issue by Djokix98** [Siccity/GLTFUtility#153]
Im struggling to make the loading work, and the only thing i managed to do is to download a .glb file from web and then load it with bytes at runtime. This works completely fine.
However, how do i load a gltf file at runtime? considering that the downloading of other files like textures is already handled and everything is located in the same folder:
- CesiumMilkTruck.gltf
- CesiumMilkTruck_Data.bin
- CesiumMilkTruck.jpg

Even when i put the whole folder into Assets folder manually, and then try to load it from there at runtime with Importer.LoadFromFile(), it still throws this error: GLTFImage.cs ToTexture2D() ERROR: Cannot connect to destination host

**Comment by Siccity** [comment]
Open up the .gltf file in your IDE, find the textures/images section and see if they contain an URL. If they do, that's probably what GLTFUtility is trying to connect to
