### ISSUE TITLE
Import bug

### ISSUE THREAD

**Issue by kelvionald** [Siccity/GLTFUtility#178]
Hello. I am developing a project for a college. I can't load models from my phone. The problem is in the library while importing.
![photo_2021-12-16_23-10-58](https://user-images.githubusercontent.com/31734063/146442573-70b0df3e-b252-4468-8e90-c1c22dd57716.jpg)
![image](https://user-images.githubusercontent.com/31734063/146442659-413f09ae-e6b9-4264-96a2-8c745ca02123.png)
The problem occurs on an Android device. Everything works correctly for Windows.
Can you help me?

**Comment by Siccity** [comment]
See [known issues](https://github.com/Siccity/GLTFUtility#known-issues)

**Comment by kelvionald** [comment]
![image](https://user-images.githubusercontent.com/31734063/146524760-06d8b795-307b-4ddd-8c38-4e68ebab75cb.png)
I have included shaders in the assembly. How to reduce project build time?

**Comment by kelvionald** [comment]
![image](https://user-images.githubusercontent.com/31734063/146526936-122abc7f-e9a2-4d41-8de9-72ef060b98a9.png)
Sorry! I included extra shaders and they were the ones that took a long time to compile. Only these 4 shaders needed to be added. Everything is working! Thanks to!
