### ISSUE TITLE
GLTFUtility backface culling

### ISSUE THREAD

**Issue by marcusx2** [Siccity/GLTFUtility#181]
Model looks like this in blender:
![image](https://user-images.githubusercontent.com/5656275/149817613-918dfa6c-0338-4e9b-a36c-bc21938dcc44.png)

but in Unity, it looks like as if I had the backface culling in blender enabled:
![image](https://user-images.githubusercontent.com/5656275/149817674-95e825b0-03ba-4525-a321-68d967db7e7c.png)

How can I disable backface culling with GLTFUtility?

**Comment by Siccity** [comment]
You can make a shader in Unity that supports backface culling. This is not standard, however. I suggest just fixing your normals in blender.
