### ISSUE TITLE
No functionality during Build

### ISSUE THREAD

**Issue by neubern** [Siccity/GLTFUtility#19]
I´ve posted this in the Unityforums. But since both are related, i´m posting it also here.
Link to the original post: https://forum.unity.com/threads/gltf-unity-bug-missing-feature-wrong-behaviour.731120/

The user run the application. A File Opener dialog is open, in which the user selects the GLTF File to be loaded. The File is loaded and is shown in screen.

The problem:
Everything works perfect in Editor. In Build nothing seems to work.
This occurs NOT ONLY with the "UniGLTF" from @Siccity but also the UnityGLTF from @Khronos

Link to the project: https://drive.google.com/open?id=1ThMY27BhH9Uxqg3kSUWMcKjHBZib5YDX

**Comment by Siccity** [comment]
This isn't UniGLTF and I did not create nor participate in the creation of UniGLTF.
Is this GLTFUtility related?

As indicated in the [readme](https://github.com/Siccity/GLTFUtility/blob/master/README.md), runtime import API is not finished yet, although you can try experimenting with `GLTFObject.Load(filepath);` followed by `glTFObject.Create();`
