### ISSUE TITLE
Improve glTF plugin compatibility with newer ScriptedImporterAttribute syntax

### ISSUE THREAD

**Issue by bitinn** [Siccity/GLTFUtility#191]
**Is your feature request related to a problem? Please describe.**

I am testing interoperability across various glTF plugins for Unity, and run into an issue between multiple ScriptedImporter declaring itself as default importer for `glb` or `gltf` file type.

Unity will disable all importers for `glb` and `gltf` files upon seeing this, and [an error are logged](https://github.com/Unity-Technologies/UnityCsReference/blob/master/Modules/AssetPipelineEditor/Public/ScriptedImporter.cs#L116):

> Multiple scripted importers are targeting the extension 'glb' and have all been rejected: ...

**Describe the solution you'd like**

[This fork of UnityGLTF](https://github.com/prefrontalcortex/UnityGLTF) is the only plugin that doesn't conflict with other glTF importer via the use of `overrideExts` in ScriptedImporterAttribute (an added feature since 2020.2).

https://docs.unity3d.com/2022.2/Documentation/ScriptReference/AssetImporters.ScriptedImporterAttribute.html
https://github.com/prefrontalcortex/UnityGLTF/blob/master/UnityGLTF/Assets/UnityGLTF/Editor/Scripts/GLTFImporter.cs#L24

**Describe alternatives you've considered**

N/a

**Additional context**

I have tested this change to work:

![Screenshot 2022-03-04 140543](https://user-images.githubusercontent.com/1484279/156710978-ff3e9138-3c63-4029-a66a-6d9504d99c20.jpg)

(This is a cross-post from https://github.com/atteneder/glTFast/issues/352)

**Comment by bitinn** [comment]
Bad news: if no plugin declare `exts` for a file extension (eg. they all declare `overrideExts` only), then under Unity 2022.2.x at least, no Inspector will show up; but if there is more than 1 plugin declare `exts` for a file extension, then Unity disable all of them...

I will follow up with Unity soon.

https://github.com/prefrontalcortex/UnityGLTF/issues/37#issuecomment-1058886899

**Comment by bitinn** [comment]
Side note: these are the compatibility of GLB file across various popular glTF plugins.

![Export-Table](https://user-images.githubusercontent.com/1484279/156728714-733d82b1-2289-4bdb-bb6e-575f3955c0e2.jpg)

**Comment by hybridherbst** [comment]
Opened a PR to fix this with the same pattern as glTFast and UnityGLTF are now using: 
- https://github.com/Siccity/GLTFUtility/pull/193
