### ISSUE TITLE
Add support for LWRP / HDRP pipelines for import

### ISSUE THREAD

**Issue by Clavus** [Siccity/GLTFUtility#20]
I noticed that on my import into a LWRP project (Unity 2019.2.3), the materials on the imported model were entirely magenta. The shaders GLTFUtility uses to generate materials do not support the custom render pipelines by default.

**Comment by Clavus** [comment]
I've 'hacked' this into my own fork of the project by grabbing the GraphicsSettings.renderPipelineAsset.defaultShader and using that as the material shader in GLTFMaterial.OnLoad

**Comment by Siccity** [comment]
Can you open a pull request with this change?
Does it break comparability with standard RP?

**Comment by Clavus** [comment]
It doesn't break compatibility with standard RP but I've only added it for the metallic material workflow. In short what I did in PbrMetalRoughness.OnLoad:

```
Shader sh = GraphicsSettings.renderPipelineAsset?.defaultShader;
if (sh == null)
{
	Material = new Material(Shader.Find("GLTFUtility/Standard (Metallic)"));
}
else
{
	Material = new Material(sh);
}

[...]

// After the texture and color is extracted from the glTFObject
if (Material.HasProperty("_BaseMap"))
	Material.SetTexture("_BaseMap", Material.mainTexture);
if (Material.HasProperty("_BaseColor"))
	Material.SetColor("_BaseColor", baseColor);
```


Which did the trick for me for importing some stuff in LWRP. The default shader used most of the same properties.

**Comment by Siccity** [comment]
Alright, thanks. I'll add the update when I get some time on my hands.
