### ISSUE TITLE
Not able to use

### ISSUE THREAD

**Issue by rupeshpamaihgari** [Siccity/GLTFUtility#21]
Hi,
I am using this GLTF for first time and GLTFUtility looks more promising than UnityGLTF. But when I downloaded unitypackage, I am unable to use it in project. May be a small documentation on how to use will help

**Comment by pachermann** [comment]
thanks for sharing this!

i tried exporting a FBX animation from hierarchy in unity, but when sleecting the export selection - .glb  nothing happens

**Comment by Siccity** [comment]
Export is in development, but it will take some time before it is completed
