### ISSUE TITLE
possibility of changing shaderd

### ISSUE THREAD

**Issue by giulianamuto** [Siccity/GLTFUtility#219]
hello,
i am using glft for the runtime import of glb objects. I was wondering if it is possible to use my shader instead of the ones you propose. It's a very important optimisation issue and your shaders kill my performance, is there a way to do it ? :)

**Comment by Siccity** [comment]
You can set the shaders with the import options, both in editor and through the API

**Comment by giulianamuto** [comment]
how can i do it?
