### ISSUE TITLE
Add async/multithreaded import support

### ISSUE THREAD

**Issue by luizcarlosfx** [Siccity/GLTFUtility#23]
I liked the way you are organizing this project, it's much better than UnityGLTF from Khronos Group. But the only reason I'm not switching to your project now is that your product seems to be better used in the editor, not runtime, since you don't support async importing yet

**Comment by Siccity** [comment]
Thanks :)
By async import, are you referring to being able to load files with textures from external sources?

**Comment by luizcarlosfx** [comment]
Actually I mean, importing from external sources without freezing the main thread. Using threads and/or coroutines

**Comment by Siccity** [comment]
Ah I see. I don't have much experience with async but I'll have to get around it when loading resources from the web anyway, so it's on the roadmap.

**Comment by Siccity** [comment]
Multithreading added in e79f3daeb992f733ce3b270cd72dc19e18e15ada
