### ISSUE TITLE
Not possible to update shader's materials

### ISSUE THREAD

**Issue by kenorb** [Siccity/GLTFUtility#233]
I've imported .glb avatar, but Shader's Materials are read-only and it's not possible to modify them (like changing the colors or texture). Normally when I import .fbx object into a scene, I can modify materials, so new values are updated in .meta file.

Is it a feature, bug or by design?

**Comment by kenorb** [comment]
Ok, as for the workaround, it's possible to drag and drop into the object on the scene, it'll replace the old materials, and the new info is stored into scene file. I think that would do.

**Comment by Siccity** [comment]
It's by design to replicate what the built-in FBX importer does.
The materials are imported as they are from the file itself.
The solution is to create and use your own materials like the way you did.
