### ISSUE TITLE
Add draco compression support

### ISSUE THREAD

**Issue by Siccity** [Siccity/GLTFUtility#27]
[glb.zip](https://github.com/Siccity/GLTFUtility/files/3650856/glb.zip)

_Originally requested by @umresh in https://github.com/Siccity/GLTFUtility/issues/26#issuecomment-534875971_

**Comment by umresh** [comment]
Hi, When can you add the draco support. Thanks

**Comment by Siccity** [comment]
I don't know. Perhaps after I'm done with async import

**Comment by umresh** [comment]
Hi, any update on draco support.

**Comment by Siccity** [comment]
Currently in progress. I haven't had much time to work on it since I just moved.
I was trying to find a way to make plug-ins optional but it's very hard, so I might just end up hardcoding Draco support into GLTFUtility. But a problem with Google's Draco plug in is that it requires your project to allow unsafe code. I am not a fan of putting such requirements on my users.

**Comment by naveenan-alt** [comment]
Have you added support for draco compression?

**Comment by mschneider** [comment]
You could precompile the DLL containing the unsafe code, this would allow you to use it without requiring the user to compile their own unsafe code.

**Comment by mschneider** [comment]
Using an assembly definition file it should also be possible to configure the unsafe flag only for a certain namespace / compilation unit. Have a look here: https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

**Comment by Siccity** [comment]
Good call @mschneider 
Marking allow unsafe on the assembly definition sounds like a great solution

**Comment by umresh** [comment]
Hey any update? Or could you point me in right direction how to do it?

**Comment by IsmaeelGoraya** [comment]
Any update on this?

**Comment by Siccity** [comment]
Unfortunately not yet, no

**Comment by leon** [comment]
We really need the draco support for our AR app.

@Siccity Would it be possible to pay you to fix it?

**Comment by Siccity** [comment]
@leon 
Yes It'd be possible. Send me an email with your deadline and I'll see if I got the time for it.

**Comment by Siccity** [comment]
Draco is now finally supported! 08ec501b78954fb91ff27f7d7404f496eb39c0d6
