### ISSUE TITLE
Normal map issue

### ISSUE THREAD

**Issue by umresh** [Siccity/GLTFUtility#28]
When I load a model its normal map is messed up when I load model from byte[].

![image](https://user-images.githubusercontent.com/6183803/65669051-7ff8ba00-e060-11e9-973f-2c90643a3942.png)

**Comment by Siccity** [comment]
Please attach the file.

**Comment by umresh** [comment]
I'm Downloading the file using unity downloader and Passing the byte[] to decode.


[BoomBox.zip](https://github.com/Siccity/GLTFUtility/files/3657860/BoomBox.zip)

**Comment by Siccity** [comment]
Try with the recent update. A lot of changes have been made to the way normal maps are being handled.
