### ISSUE TITLE
Error loading monster GLB example file

### ISSUE THREAD

**Issue by lucasmontec** [Siccity/GLTFUtility#35]
Model:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Monster/glTF-Binary

Error:
Mesh 'monster': abnormal mesh bounds - most likely it has some invalid vertices (+/-inifinity or NANs) due to errors exporting.
Mesh bounds min=(-451080789585213150228586868600995840.00, -117474783433508707118662977875045515264.00, -inf), max=(201716128847098024439223546364158803968.00, 124780588502382453412050473577273622528.00, inf). Please make sure the mesh is exported without any errors.

Failed setting triangles. Some indices are referencing out of bounds vertices. IndexCount: 2652, VertexCount: 780
UnityEngine.Mesh:SetTriangles(Int32[], Int32)
Siccity.GLTFUtility.MeshData:ToMesh() (at Assets/GLTFUtility/Scripts/Spec/GLTFMesh.cs:123)
Siccity.GLTFUtility.ImportTask:OnMainThreadFinalize() (at Assets/GLTFUtility/Scripts/Spec/GLTFMesh.cs:205)
Siccity.GLTFUtility.ImportTask`1:RunSynchronously() (at Assets/GLTFUtility/Scripts/Importer.cs:96)
Siccity.GLTFUtility.Importer:LoadInternal(GLTFObject, String, ImportSettings, ImportResult[]&) (at Assets/GLTFUtility/Scripts/Importer.cs:140)
Siccity.GLTFUtility.Importer:ImportGLB(String, ImportSettings, ImportResult[]&) (at Assets/GLTFUtility/Scripts/Importer.cs:69)
Siccity.GLTFUtility.Importer:LoadFromFile(String, ImportSettings, ImportResult[]&, Format) (at Assets/GLTFUtility/Scripts/Importer.cs:31)
Siccity.GLTFUtility.Importer:LoadFromFile(String, Format) (at Assets/GLTFUtility/Scripts/Importer.cs:16)
Modules.Model.GltfModelLoader:LoadModel(String, Action`1) (at Assets/_Mondo/SubModules/Modules/Modules/Model/Scripts/GltfModelLoader.cs:17)
Modules.Model.ModelController:OnModelDownloaded(String) (at Assets/_Mondo/SubModules/Modules/Modules/Model/Scripts/ModelController.cs:80)
Modules.Model.<>c__DisplayClass5_0:<DownloadFile>b__0(String) (at Assets/_Mondo/SubModules/Modules/Modules/Model/Scripts/CachedModelDownloader.cs:89)
Modules.Model.<DownloadFile>d__8:MoveNext() (at Assets/_Mondo/SubModules/Modules/Modules/Model/Scripts/CachedModelDownloader.cs:175)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by Siccity** [comment]
I noticed monster.glb defines a byteStride property in some of its bufferViews. GLTFUtility currently does not support byteStride

**Comment by Siccity** [comment]
Apparently this model was problematic so they pulled it from the example repo.
https://github.com/KhronosGroup/glTF-Sample-Models/commit/5694dc562b0f34bd32e8dbd21776aa2dc58e191c
