### ISSUE TITLE
Errors in Unity 2018.3.8f

### ISSUE THREAD

**Issue by Paegasus** [Siccity/GLTFUtility#5]
<img src="https://i.imgur.com/3d6Jn6t.jpg"></img>

Wanted to give this plugin a try, been using Khrono's UnityGLTF plugin so far,
but when I drag and drop a *.glb file I get a few errors in the latest Unity version,
and the import fails, some help would be appreciated, thanks.

**Comment by Siccity** [comment]
I'll need the .glb to find out what's wrong.
I've been going up and down the collection of test models at https://github.com/KhronosGroup/glTF-Sample-Models.git all day, fixing as much as i can, but the more sample models the better.

**Comment by Paegasus** [comment]
Thanks for the help, I appreciate your work, here is the file I was trying to import.
[Cube.zip](https://github.com/Siccity/GLTFUtility/files/3025936/Cube.zip)

**Comment by Paegasus** [comment]
Alright, I downloaded the latest commit, and it seems to be working fine now, thanks a lot,
it already looks like a great alternative to Khronos' UnityGLTF.
<img src="https://i.imgur.com/kHGQuSq.jpg"><image>

**Comment by Siccity** [comment]
Thanks for the update! Was just about to test it myself. And I'm glad you think so :)

Don't hesitate to come back if you encounter more issues

**Comment by Paegasus** [comment]
I will, for sure. :)
