### ISSUE TITLE
Tinkercad GLB model import issue

### ISSUE THREAD

**Issue by TheFearlessHobbit** [Siccity/GLTFUtility#50]
I imported a colored glb model at runtime but the colors didn't display. I created the model online using [Tinkercad](https://www.tinkercad.com/). Imported it under the Lightweight Render Pipeline within Unity. The colors seem to work if I remove the Lightweight Render Pipeline script in the graphics settings. To replicate: 

- Import Lightweight RP package 
- Create -> Rendering -> Lightweight Render Pipeline -> Pipeline Asset
- Edit -> Project Settings -> Graphics and use the newly created pipeline asset in Scriptable Render Pipeline Settings 
- Import any model from Tinker with some color data other than white/gray (either at runtime or editor)

**Comment by Siccity** [comment]
I don't have any experience with LRP. Is your model using vertex colors? It may be that my shaders, which incorporate vertex color tint, don't work in LRP.
