### ISSUE TITLE
Namespace 'Newtonsoft' could not be found

### ISSUE THREAD

**Issue by garysb** [Siccity/GLTFUtility#53]
After adding the required entries into the package manifest.json, I am receiving multiple entries of the error:

error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

My manifest:
```
    ...
    "com.unity.multiplayer-hlapi": "1.0.4",
    "com.unity.nuget.newtonsoft-json": "1.1.2",
    "com.siccity.gltfutility": "https://github.com/siccity/gltfutility.git",
    "com.unity.test-framework": "1.1.9",
    "com.unity.textmeshpro": "2.0.1",
    "com.unity.timeline": "1.2.10",
    "com.unity.ugui": "1.0.0",
    ...
```

Should there be an entry in the GLTFUtility.asmdef and if so, what should it me?

**Comment by Siccity** [comment]
Can you access Newtonsoft from scripts outside the GLTFUtility folder? If not, it might be a problem with the unity package manager.
I don't need to reference Newtonsoft in the asmdefs on my end, so that shouldn't be the problem.

**Comment by Eisenspalter** [comment]
I have the same error message. Unity 2020.3.18f1
