### ISSUE TITLE
Render Queue

### ISSUE THREAD

**Issue by florolf1** [Siccity/GLTFUtility#61]
Some parts of the model are not rendered correctly in the editor as well as on the end device only at certain camera positions.
![Bildschirmfoto 2020-02-24 um 13 19 17](https://user-images.githubusercontent.com/29608141/75152620-c0408f00-5709-11ea-8b14-90c71bc1c7d0.png)
![Bildschirmfoto 2020-02-24 um 13 20 33](https://user-images.githubusercontent.com/29608141/75152628-c7679d00-5709-11ea-9031-617346f49b36.png)

I suspect that this is due to the render queue of transparent materials.
![Bildschirmfoto 2020-02-24 um 13 21 35](https://user-images.githubusercontent.com/29608141/75152643-cfbfd800-5709-11ea-9a14-27e8aaa849bb.png)
![Bildschirmfoto 2020-02-24 um 13 21 58](https://user-images.githubusercontent.com/29608141/75152644-d2223200-5709-11ea-968a-5428a2fccb44.png)

If I include GLTFUtiliy as .unitypackage in my project, the import module is not available to me, so the GLTF shaders are not used and the model is displayed correctly.

![Bildschirmfoto 2020-02-24 um 13 31 00](https://user-images.githubusercontent.com/29608141/75152701-f54ce180-5709-11ea-9781-c11fdb96e7b1.png)

As soon as I add GLTFUtiliy to the package.json file, the import window is available to me and the corresponding shaders are used.
![Bildschirmfoto 2020-02-24 um 13 30 42](https://user-images.githubusercontent.com/29608141/75152690-ed8d3d00-5709-11ea-8663-d505d45a827b.png)

**Comment by Siccity** [comment]
The problem has to do with how Unity renders transparent objects. To fix it, use less transparent materials or split your mesh into multiple objects
https://answers.unity.com/questions/609021/how-to-fix-transparent-rendering-problem.html

**Comment by florolf1** [comment]
I read the article already. Unfortunately this is not the answer for me. Thanks for the quick answer!

**Comment by Siccity** [comment]
Can you share your model so I can have a look at it?

**Comment by florolf1** [comment]
I've sent you an email.
Thanks.

**Comment by Siccity** [comment]
I tested your model and everything is using transparent materials as I said. Don't use transparent shaders for things that are not transparent, and set each objects pivot near the object to help Unity sort the remaining transparent materials.

**Comment by florolf1** [comment]
Because the model was not created by me, I have no access to the metadata.
However, this problem also occurs with models that I have created myself. Maybe the reason is the program the models are created in. (Autodesk Revit). 

Is there a way to extract the materials so that I can assign a different shader to them without having to recreate each material and assign it to the objects?

Thanks for your support! (y)

**Comment by Siccity** [comment]
GLTFUtility will assign transparent shaders to transparent objects, and opaque shaders to opaque objects. Your file has every object set to transparent, so GLTFUtility sees them all the same. 

There are options for replacing import shaders in the "Shader Overrides" section, but doing it this way will also affect your actually transparent materials like glass. 

Currently there is only one way to extract materials, by selecting them all in the project window and hit Ctrl+D.

**Comment by florolf1** [comment]
When I extract the materials and set the Shader Queue from 3000 to >3000 (e.g. 3100), the model is displayed correctly. 
But I would have to do this manually for all materials and then assign them to the corresponding part in the model.

Is it possible to set the Render Queue in your plugin?

**Comment by florolf1** [comment]
I found a way, but that wont work if all materials have the same render queue..

**Comment by florolf1** [comment]
Problem solved, it had nothing to do with your work.
Thanks for the support!
