### ISSUE TITLE
Can't load animation

### ISSUE THREAD

**Issue by ITEnot** [Siccity/GLTFUtility#63]
Error ocured when I tried import glb with animation
"Can't use AnimationClip::SetCurve at Runtime on non Legacy"
Suggested fix: 
set new created animation type to legacy in GLTFAnimation.cs
`result.clip.legacy = true;`

**Comment by Siccity** [comment]
Where in the code does this error happen?

ImportSettings already has a useLegacyAnimations setting

**Comment by ITEnot** [comment]
stacktrace
`Error Unity: Can't use AnimationClip::SetCurve at Runtime on non Legacy AnimationClips
Error Unity: UnityEngine.AnimationClip:SetCurve(String, Type, String, AnimationCurve)
Error Unity: Siccity.GLTFUtility.GLTFAnimation:Import(ImportResult[], ImportResult[]) (at \GLTFUtility-master\Scripts\Spec\GLTFAnimation.cs:106)
Siccity.GLTFUtility.GLTFAnimationExtensions:Import(List`1, ImportResult[], ImportResult[]) (at \GLTFUtility-master\Scripts\Spec\GLTFAnimation.cs:138)
Error Unity: Siccity.GLTFUtility.Importer:LoadInternal(GLTFObject, String, ImportSettings, ImportResult[]&) (at \GLTFUtility-master\Scripts\Importer.cs:145)
Error Unity: Siccity.GLTFUtility.Importer:ImportGLB(String, ImportSettings, ImportResult[]&) (at C:\Users\ITEnot\UnityProjects\ru.likevr.arselfie\Assets\0_alex_folders\GLTFUtility-master\Scripts\Importer.cs:69)
Error Unity: Siccity.GLTFUtility.Importer:LoadFromFile(...)`

**Comment by ITEnot** [comment]
Sorry
It turned out that I am using the old version of gltfUtility without valid ImportSettings
