### ISSUE TITLE
Glb not loading on demo project

### ISSUE THREAD

**Issue by umresh** [Siccity/GLTFUtility#65]
Tried your demo project and while loading this glb [https://unity-video.s3-ap-southeast-1.amazonaws.com/181C41E3-653C-4AD6-B76F-F4AE1553FFF3.glb](url) its giving error saying
TestLoader: loading failed!

**Comment by Siccity** [comment]
There is nothing called "TestLoader" in GLTFUtility, and no error message saying "loading failed"
