### ISSUE TITLE
async sample code has a bug

### ISSUE THREAD

**Issue by HawkenKing** [Siccity/GLTFUtility#69]
```cs
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Siccity.GLTFUtility;
public class ModelLoader : MonoBehaviour
{
    public string filename;
    public void OnLoadTest()
    {
        ImportGLTFAsync(filename);
    }
    void ImportGLTFAsync(string filepath) {
        Importer.ImportGLTFAsync(filepath, new ImportSettings(), OnFinishAsync);
    }
    void OnFinishAsync(GameObject result) {
        Debug.Log("Finished importing " + result.name);
    }
}
```

OnFinishAsync will redline in VSCode and Unity (line 13)

Is there a way to correct the third part of Importer.ImportGLTFAsync() to fix this?

**Comment by HawkenKing** [comment]
fixed for now like this:

void ImportGLTFAsync(string filepath) {
        Importer.ImportGLTFAsync(filepath, new ImportSettings(), OnFinishAsync);
    }
    void OnFinishAsync(GameObject result, GLTFAnimation.ImportResult[] air) {
        Debug.Log("Finished importing " + result.name);
    }

**Comment by robotvsn** [comment]
I think I'm having the same issue. The suggested fix is also not working.
The async example code won't compile. It says:

`cannot convert from 'method group' to 'Action<GameObject, AnimationClip[]>'`

![grafik](https://user-images.githubusercontent.com/32981228/81481457-ac98c500-9230-11ea-8642-526f5f15fc63.png)

Did anything change in the source code?

**Comment by Siccity** [comment]
Try adding `, AnimationClip[] animations` to OnFinishAsync paramers

**Comment by debfdias** [comment]
Hi, @Siccity . I tried your suggested fix, but still didn't work. Any idea of what may fix this? It works fine when i want to load a single .gltf file, but doesn't load the textures when they aren't embeded in the file.

**Comment by Thebinoman** [comment]
> , AnimationClip[] animations

This worked for me. Maybe change the code on the readme file?
