### ISSUE TITLE
value cannot be null

### ISSUE THREAD

**Issue by MicleBrick** [Siccity/GLTFUtility#74]
attempting to import glb file, getting this error
![image](https://user-images.githubusercontent.com/6323125/79670646-9d26de80-8192-11ea-98a8-665016a681a1.png)

**Comment by ozgurozansen** [comment]
Same here after the "Import returns AnimationClip[] instead of GLTFAnimation.ImportResult[]" update. 
![err](https://user-images.githubusercontent.com/34624697/79730092-a037e100-82f0-11ea-8518-0b48cad2a811.PNG)



"
