### ISSUE TITLE
Support for URP shader

### ISSUE THREAD

**Issue by dblatner** [Siccity/GLTFUtility#75]
Hey there!

Wether using GLTFUtility for VR or mobile application, URP would boost performance a lot. This would be the first GLTF solution supporting URP at the moment.

Probably the only thing to update is:
- have a compile-time check if URP is used
- if URP then: change shader references from standard shaders/materials to URP shaders in the material importer

What do you think?

**Comment by Siccity** [comment]
Sounds simple enough. I can try, but I have no experience with URP.

**Comment by Stanke17** [comment]
Any update on this?

**Comment by marcusx2** [comment]
Please, URP is a must for mobile projects. Specially WebGL. I am not sure, but is URP already supported? This [pull request](https://github.com/Siccity/GLTFUtility/pull/84) seems to indicate that. But I still can't use URP, please see [this](https://github.com/Siccity/GLTFUtility/issues/90).

**Comment by Siccity** [comment]
Just added basic URP support. Please verify that the shaders work correctly.

**Comment by marcusx2** [comment]
It works! Just one thing, it seems to add a metallic material to the model for no reason. There is no metallic material in the original model, is there a way to configure this?

**Comment by Siccity** [comment]
@marcusx2 In normal PBR rendering conditions, a material is either metallic or specular. The model you are using is exported using metallic settings. GLTFUtility is correct to use metallic shader, and I assume both sketchfab and Piglet does the same. I think the problem here is that I set up the material wrong, due to my inexperience with URP. You can edit the default shaders in `GLTFUtility/Materials/URP`. If you are able to spot the issue I can fix it.

**Comment by marcusx2** [comment]
@Siccity Oh I see. Sorry, I don't know the next thing about shaders either! Maybe you can try [Unity Discord]( https://discord.gg/unity)? They have a shader channel there.

**Comment by Siccity** [comment]
I just committed a small fix for the materials. I found that i had hooked the roughness input to the metallic output, and not hooked the metallic input to anything. Now it's all hooked up and hopefully looks better!

**Comment by marcusx2** [comment]
Thanks! It's working perfectly now. Is there a way that I can edit the materials in the editor without having to create a copy? I mean 
![image](https://user-images.githubusercontent.com/5656275/92658657-549cc880-f2cd-11ea-96bc-6ce667b650a6.png) clicking on the material right there and editing it.

**Comment by marcusx2** [comment]
@Siccity There is also one problem...aren't animations supported? The animation is not playing. There is one animation clip called "All Animations", but nothing happens when I try to play it. Even if I add an animation component to the prefab on the scene and attach the clip to it.

**Comment by Siccity** [comment]
@marcusx2 this is the default way Unity does it. You can't edit source materials on fbx or obj either. I might make a setting in the future that exports these source materials as editable copies
