### ISSUE TITLE
Add Material Texture Animation Support

### ISSUE THREAD

**Issue by diegodelarocha** [Siccity/GLTFUtility#77]
Found another way that might work for Adding Texture Offset Animation Support?

Not sure if this is supported on the GLTF spec, but there is an addon in blender called [Images as Planes](https://docs.blender.org/manual/en/latest/addons/import_export/images_as_planes.html). It basically lets you animate textures on a material on an `Offset` parameter, and from what I can see it just uses the basic Texture Node. So If this could somehow be hooked to the `Offset` parameter on Unity's Material, would be rad 🤓 .

Here's an example gif, and the blender and GLTF files ⬇️

![UVImageSeqAnim](https://user-images.githubusercontent.com/20521814/82125788-44307300-975d-11ea-9b80-d97f702e29f2.gif)

[UVImageSeqTest.zip](https://github.com/Siccity/GLTFUtility/files/4638801/UVImageSeqTest.zip)

**Comment by Siccity** [comment]
This isn't part of the GLTF spec but should be relatively easy for any programmer to implement outside the plugin

**Comment by diegodelarocha** [comment]
Ah, thanks for looking into this 🙏, I'll see how to do this outside of the plug-in then 🤓
