### ISSUE TITLE
Error loading texture from disk

### ISSUE THREAD

**Issue by jonasolof** [Siccity/GLTFUtility#79]
When trying to load any .gltf file from a local path I run into the error when loading textures.

Code I'm running:
`
GameObject model = Importer.LoadFromFile(aPathInMyAssetFolderOrElsewhereOnMyDisk);
`

Console says:
`Invalid AssetDatabase path: /Users/me/Library/Application Support/DefaultCompany/ProjectName/Files/GLTF_Models/Model/texture.jpg. Use path relative to the project folder.`

It doesn't matter if the gltf is within our outside the project folder.

As well as:
`GLTFImage.cs ToTexture2D() ERROR: Cannot connect to destination host
UnityEngine.Debug:LogError(Object)
Siccity.GLTFUtility.<CreateTextureAsync>d__3:MoveNext() (at Assets/Plugins/GLTFUtility-master/Scripts/Spec/GLTFImage.cs:65)
Siccity.GLTFUtility.<GetTextureCached>d__3:MoveNext() (at Assets/Plugins/GLTFUtility-master/Scripts/Spec/GLTFTexture.cs:29)
Siccity.GLTFUtility.<CreateMaterial>d__5:MoveNext() (at Assets/Plugins/GLTFUtility-master/Scripts/Spec/GLTFMaterial.cs:166)
Siccity.GLTFUtility.<CreateMaterial>d__14:MoveNext() (at Assets/Plugins/GLTFUtility-master/Scripts/Spec/GLTFMaterial.cs:42)
Siccity.GLTFUtility.<OnCoroutine>d__4:MoveNext() (at Assets/Plugins/GLTFUtility-master/Scripts/Spec/GLTFMaterial.cs:318)
Siccity.GLTFUtility.ImportTask1:RunSynchronously() (at Assets/Plugins/GLTFUtility-master/Scripts/Importer.cs:161)
Siccity.GLTFUtility.Importer:LoadInternal(GLTFObject, String, Byte[], Int64, ImportSettings, AnimationClip[]&) (at Assets/Plugins/GLTFUtility-master/Scripts/Importer.cs:205)
Siccity.GLTFUtility.Importer:ImportGLTF(String, ImportSettings, AnimationClip[]&) (at Assets/Plugins/GLTFUtility-master/Scripts/Importer.cs:141)
Siccity.GLTFUtility.Importer:LoadFromFile(String, ImportSettings, AnimationClip[]&, Format) (at Assets/Plugins/GLTFUtility-master/Scripts/Importer.cs:32)
Siccity.GLTFUtility.Importer:LoadFromFile(String, Format) (at Assets/Plugins/GLTFUtility-master/Scripts/Importer.cs:16)
FirebaseGLTFLoader:LoadModel(String) (at Assets/FirebaseGLTFLoader.cs:77)
FirebaseGLTFLoader:DebugMethod() (at Assets/FirebaseGLTFLoader.cs:26)`

I realise that this might be down to user error but if so I'd be happy to be corrected on how to use this tool correctly! 

I can't understand how to run `Importer.LoadFromFile` with a local path that perhaps would make `UnityEditor.AssetDatabase.LoadAssetAtPath()` happy...

**Comment by tejpratap0** [comment]
I am using following line of code in public **IEnumerator CreateTextureAsync(bool linear, Action<Texture2D> onFinish, Action<float> onProgress = null)** in this method of GLTFImage class. Working fine on Windows & Android.

string path = "C:/Users/GreyKernel/AppData/LocalLow/GK/AppName/Temp/textures/BaseMap.png";
Texture2D texture = null;					
texture = new Texture2D(2, 2, TextureFormat.ARGB32, true, true);					
byte[] bytes = File.ReadAllBytes(path);					
if (texture.LoadImage(bytes))					
{						
	texture.Apply();					
	texture.name = Path.GetFileNameWithoutExtension(path); 
	Debug.Log("Loading Texture: " + Path.GetFileNameWithoutExtension(path) + ", Size: " + bytes.Length);  
}				
mat.SetTexture("_BaseMap", texture);

**Comment by Siccity** [comment]
Both the texture and gltf file has to be inside the assets folder. GLTFUtility uses this automatically when importing glft files into the unity editor. This feature does not work in runtime.
