### ISSUE TITLE
Distorted meshes when importing large files.

### ISSUE THREAD

**Issue by ozgurozansen** [Siccity/GLTFUtility#80]
Meshes are distorted when importing files with larger than 65536 vertices.

Actually, there is a very simple workaround for this:
adding a line (line 180)

> `mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;`

into the `ToMesh()` function of `GLTFMesh.cs` file solves the issue. Should I make a branch commit?

**Comment by Siccity** [comment]
Yes that would be nice, thank you

**Comment by ozgurozansen** [comment]
Just created a pull request https://github.com/Siccity/GLTFUtility/pull/81
