### ISSUE TITLE
issue with meshes containing more than 65535 vertices

### ISSUE THREAD

**Issue by berry4u** [Siccity/GLTFUtility#87]
Hi.
I noticed that GLTFUtility does't shape correctly meshes with more than 65536 vertices.
Likely this is due to the missed set of mesh indexFormat which in that case must be UnityEngine.Rendering.IndexFormat.UInt32.
Could you take a look on this issue?

Thank you 

Berardo

**Comment by Siccity** [comment]
I thought this solved that b0321ee8653a5f2bdf168ad3e0f8fe7b3c959afa
Are you using the newest version?

**Comment by berry4u** [comment]
You guessed. My version is not updated and I was not aware of the closed issue.

Sorry for that.

Thank you
