### ISSUE TITLE
JsonReaderException

### ISSUE THREAD

**Issue by DirtyFreddie** [Siccity/GLTFUtility#88]
This is how i try to use it. none of them works

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Siccity.GLTFUtility;

public class MyImporter : MonoBehaviour
{
	public string path;

	[ContextMenu("ImportTest")]
	private void ImportTest()
	{
		ImportGLTF(path);
	}

	[ContextMenu("AsyncImportTest")]
	private void AsyncImportTest()
	{
		ImportGLTFAsync(path);
	}

	void ImportGLTF(string filepath)
	{
		GameObject result = Importer.LoadFromFile(filepath);
	}

	void ImportGLTFAsync(string filepath)
	{
		Importer.ImportGLTFAsync(filepath, new ImportSettings(), OnFinishAsync);
	}

	void OnFinishAsync(GameObject result, AnimationClip[] animationClip)
	{
		Debug.Log("Finished importing " + result.name);
	}
}

Here is the error for normal import:

JsonReaderException: Additional text encountered after finished reading JSON content: �. Path '', line 26440, position 1.
Newtonsoft.Json.JsonTextReader.Read () (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Siccity.GLTFUtility.Importer.ImportGLB (System.String filepath, Siccity.GLTFUtility.ImportSettings importSettings, UnityEngine.AnimationClip[]& animations) (at Assets/Scripts/Importer.cs:68)
Siccity.GLTFUtility.Importer.LoadFromFile (System.String filepath, Siccity.GLTFUtility.ImportSettings importSettings, UnityEngine.AnimationClip[]& animations, Siccity.GLTFUtility.Format format) (at Assets/Scripts/Importer.cs:31)
Siccity.GLTFUtility.Importer.LoadFromFile (System.String filepath, Siccity.GLTFUtility.Format format) (at Assets/Scripts/Importer.cs:16)
MyImporter.ImportGLTF (System.String filepath) (at Assets/_Assets/MyImporter.cs:26)
MyImporter.ImportTest () (at Assets/_Assets/MyImporter.cs:13)

Here is the error for async import:
JsonReaderException: Unexpected character encountered while parsing value: g. Path '', line 0, position 0.
Newtonsoft.Json.JsonTextReader.ParseValue () (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.JsonTextReader.Read () (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.JsonReader.ReadAndMoveToContent () (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Siccity.GLTFUtility.Importer+<>c__DisplayClass16_0.<LoadAsync>b__0 () (at Assets/Scripts/Importer.cs:227)
System.Threading.Tasks.Task`1[TResult].InnerInvoke () (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Threading.Tasks.Task.Execute () (at <437ba245d8404784b9fbab9b439ac908>:0)
Rethrow as AggregateException: One or more errors occurred.
System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Threading.Tasks.Task`1[TResult].get_Result () (at <437ba245d8404784b9fbab9b439ac908>:0)
Siccity.GLTFUtility.Importer+<LoadAsync>d__16.MoveNext () (at Assets/Scripts/Importer.cs:230)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3dc54541a2574ac7826a004a212a4332>:0)

**Comment by Siccity** [comment]
Looks like you have a glb file, not gltf. Try the glb methods.
