### ISSUE TITLE
Camera importing -90 rotation on Unity?

### ISSUE THREAD

**Issue by diegodelarocha** [Siccity/GLTFUtility#92]
Hi :) 

I might be wrong, but i think the camera's rotations are having the same bug the geos/armatures used to have where they are imported into Unity rotated towards another side?

**Comment by jdcole** [comment]
@diegodelarocha See https://github.com/Siccity/GLTFUtility/pull/137. Camera just needed to be spun 180 degrees.

**Comment by Siccity** [comment]
Merged! Thanks @jdcole :)
