### ISSUE TITLE
JsonParserExeption

### ISSUE THREAD

**Issue by mskalash** [Siccity/GLTFUtility#93]
I`m update pakage to last version and have exception
Exception
JsonReaderException: Additional text encountered after finished reading JSON content: �. Path '', line 1, position 3133.
Newtonsoft.Json.JsonTextReader.Read () (at <00000000000000000000000000000000>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at <00000000000000000000000000000000>:0)
Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <00000000000000000000000000000000>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) (at <00000000000000000000000000000000>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) (at <00000000000000000000000000000000>:0)
Siccity.GLTFUtility.Importer.ImportGLB (System.String filepath, Siccity.GLTFUtility.ImportSettings importSettings, UnityEngine.AnimationClip[]& animations) (at <00000000000000000000000000000000>:0)
ContentLoader+<LoadFile>d__9.MoveNext () (at <00000000000000000000000000000000>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <00000000000000000000000000000000>:0)
The previous version worked fine

**Comment by Siccity** [comment]
Can you share the file?

**Comment by mskalash** [comment]
https://drive.google.com/file/d/1ULCUTmHGI8PHpnQBcJcb_H3xwLVxrQDr/view?usp=sharing

**Comment by mskalash** [comment]
https://drive.google.com/file/d/1_X7B9t33s7kmpEvpuKBOpIDNcVF27uVc/view?usp=sharing

**Comment by zxubian** [comment]
I'm getting the same error.

```
JsonReaderException: Unexpected character encountered while parsing value: g. Path '', line 0, position 0.
Newtonsoft.Json.JsonTextReader.ParseValue () (at <72bc94bec6c44acf84d97f15326490ac>:0)
Newtonsoft.Json.JsonTextReader.Read () (at <72bc94bec6c44acf84d97f15326490ac>:0)
Newtonsoft.Json.JsonReader.ReadAndMoveToContent () (at <72bc94bec6c44acf84d97f15326490ac>:0)
Newtonsoft.Json.JsonReader.ReadForType (Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) (at <72bc94bec6c44acf84d97f15326490ac>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at <72bc94bec6c44acf84d97f15326490ac>:0)
```

I'm using CesiumMan.glb from the [official gltf samples](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0).

The same model is loaded successfully when I use Importer.LoadFromFile, but causes an error when I use Importer.ImportGLTFAsync.

**Comment by Siccity** [comment]
Those are GLB files. Use one of the GLB methods to parse GLB files

**Comment by jajanpreet** [comment]
I get the same error on ImportFromFileAsync
