### ISSUE TITLE
JsonReaderException when trying to ImportGLTFAsync

### ISSUE THREAD

**Issue by zxubian** [Siccity/GLTFUtility#95]
Not sure if related to #93 or not, but I'll post as a separate issue just in case.

I'm getting this error:

```
JsonReaderException: Unexpected character encountered while parsing value: g. Path '', line 0, position 0.
Newtonsoft.Json.JsonTextReader.ParseValue () (at <72bc94bec6c44acf84d97f15326490ac>:0)
Newtonsoft.Json.JsonTextReader.Read () (at <72bc94bec6c44acf84d97f15326490ac>:0)
Newtonsoft.Json.JsonReader.ReadAndMoveToContent () (at <72bc94bec6c44acf84d97f15326490ac>:0)
Newtonsoft.Json.JsonReader.ReadForType (Newtonsoft.Json.Serialization.JsonContract contract, System.Boolean hasConverter) (at <72bc94bec6c44acf84d97f15326490ac>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at <72bc94bec6c44acf84d97f15326490ac>:0)
Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <72bc94bec6c44acf84d97f15326490ac>:0)
Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <72bc94bec6c44acf84d97f15326490ac>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) (at <72bc94bec6c44acf84d97f15326490ac>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) (at <72bc94bec6c44acf84d97f15326490ac>:0)
Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value) (at <72bc94bec6c44acf84d97f15326490ac>:0)
Siccity.GLTFUtility.Importer+<>c__DisplayClass16_0.<LoadAsync>b__0 () (at Library/PackageCache/com.siccity.gltfutility@8ab352c9e0/Scripts/Importer.cs:227)
System.Threading.Tasks.Task`1[TResult].InnerInvoke () (at <fb001e01371b4adca20013e0ac763896>:0)
System.Threading.Tasks.Task.Execute () (at <fb001e01371b4adca20013e0ac763896>:0)
Rethrow as AggregateException: One or more errors occurred.
System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) (at <fb001e01371b4adca20013e0ac763896>:0)
System.Threading.Tasks.Task`1[TResult].get_Result () (at <fb001e01371b4adca20013e0ac763896>:0)
Siccity.GLTFUtility.Importer+<LoadAsync>d__16.MoveNext () (at Library/PackageCache/com.siccity.gltfutility@8ab352c9e0/Scripts/Importer.cs:230)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <2feaf16e80004e0cadae3f2e05f2a3fa>:0)
```

I'm using CesiumMan.glb from the [official gltf samples](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0), but I've confirmed that the error occurs for any of the sample models.

I'm using the code from the readme in this repository to load the gltf. The model is loaded successfully when I use Importer.LoadFromFile, but causes an error when I use Importer.ImportGLTFAsync.

System info:
* Unity 2019.4.8f1 LTS
* Windows 10
* GLTFUtility v0.6.0 from UPM

**Comment by zxubian** [comment]
I've just realized this is a duplicate of #88.

Perhaps the GLB-specific method should be documented in the readme. There is one sync method that accepts both glb and gltf, but two separate async methods for each of the formats. As only one of them is in the readme, this is slightly confusing for new users of the library.

**Comment by marck0zz** [comment]
I don't want to open a new Issue so I'll use this because is the newer on this topic. Sorry

I have the same issue with all the glb files. My code:
` 
using Siccity.GLTFUtility;
public void ImportGLBAsync(string filepath)
    {
        Importer.ImportGLBAsync(filepath, new ImportSettings(), OnFinishGLBAsync);
    }

    void OnFinishGLBAsync(GameObject result, AnimationClip[] clips)
    {
        Debug.Log("Finished importing " + result.name);
        
    }`

The models comes from the Khronos "glTF-Sample-Models-master" and this happened with all of them (not tested all but mostly all) the same gLTF model on runtime works fine (with the respective "ImportGLTFAsync" code) , drag and drop those glb models on the Editor also works fine. 

Any advice or workaround? What am I missing here?

**Comment by marck0zz** [comment]
So, I'm stupid and I was calling ImportgLTSAsync instead of ImportGLBAsync...
