### ISSUE TITLE
Null argument when creating material with shader

### ISSUE THREAD

**Issue by JamesRBrinkmeyer** [Siccity/GLTFUtility#97]
[Player.log](https://github.com/Siccity/GLTFUtility/files/5196791/Player.log)

Getting an error when building my project and trying to import a GLTF file, When it gets to the material creation step, it errors out. I can't provide the model, but I can say that it was very recently export from Pixyz. When in editor play mode, the model imports perfectly fine.

**Comment by polytropoi** [comment]
you probably need to assign the gltf utility shaders to preload in the graphics settings, add them to the Always Included Shaders array, like 
![image](https://user-images.githubusercontent.com/1281119/92640661-3f12a900-f2a3-11ea-8afa-3a4a3880408e.png)

**Comment by JamesRBrinkmeyer** [comment]
That fixed it! Thanks!
